---
title: "프로젝트 제안서(기획서)"
author: "NASA Batttery"
date: "2024-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. 데이터 설명 및 원본 데이터 요약 결과

### (1) 분석 데이터

- 충전, 방전, 임피던스의 세가지 다른 운영과정을 적용한 리튬 이온 배터리

### (2) 실험 단계별 데이터 특징

#### 가. 충전과정(2가지 단계)

- (1) 정전류 단계(CC): 배터리는 1.5A의 일정한 전류로 충전되고 배터리의 전압이 4.2V에 도달할 때까지 계속된다.

- (2) 정전압 단계(CV): 배터리 전압이 4.2V에 도달 한 후 전압은 일정하게 유지되고 전류가 20mA로 떨어질 때까지 충전이 계속된다.

```{plot show}
dat <- read.csv("experiment/B0025.csv")
```

#### 나. 방전과정

- (1) 0.05Hz의 주파수로 4A의 정사각형 파동 로딩 프로필을 사용하여 수행되고 배터리의 전압이 각각 데이터 셀 실험 조건 시 지정된 전압값에 도달할 때까지 계속된다. 이 과정에서 배터리의 용량도 측정된다.

#### 다. 임피던스 측정

- (1) 전기화학 임피던스 분광법(EIS)을 사용하여 0.1Hz에서 5KHz까지의 주파수 스윕을 통해 이루어 지고 이를 통해 배터리 내부의 저항을 평가하여 배터리의 상태와 효율을 이해하는 데 사용된다. 여기서 임피던스랑 전기회로에서 전류가 흐를 때 회로가 가하는 반발이나 저항을 나타내는 개념이며 사람의 몸 안 상태(근육량, 체지방량, 수분량 등)를 알기 위해 인바디 검사를 하는 것과 비슷
  
#### 라. 실험 군집
- 10개의 데이터 군은 각각 방전시키는 전압의 양(2.7V~2.0V)과 실험 온도조건(24°C, 44°C), 실험종료 EOL 기준 값(정적 용량의 30%, 50% 감소 등)등의 실험 조건 차이가 있어 이에 대한 비교 분석이 가능하다.

| Name   | Age | Occupation |
|--------|-----|------------|
| John   | 28  | Engineer   |
| Doe    | 34  | Doctor     |
| Jane   | 31  | Artist     |
| Smith  | 24  | Lawyer     |



 마. 반복된 충전 및 방전 사이클을 통해 배터리 잔여 충전 및 유효 수명(RUL)을 예측하기 위한 모델의 파라미터를 유추할 수있다. 

2. 데이터 세부 설명

 가. 충전과정(2가지 단계)

  (1) 정전류 단계(CC): 배터리는 1.5A의 일정한 전류로 충전되고 배터리의 전압이 4.2V에 도달할 때까지 계속된다.

  (2) 정전압 단계(CV): 배터리 전압이 4.2V에 도달 한 후 전압은 일정하게 유지되고 전류가 20mA로 떨어질 때까지 충전이 계속된다.

 나. 방전과정

  (1) 0.05Hz의 주파수로 4A의 정사각형 파동 로딩 프로필을 사용하여 수행되고 배터리의 전압이 각각 데이터 셀 실험 조건 시 지정된 전압값에 도달할 때까지 계속된다. 이 과정에서 배터리의 용량도 측정된다.

 다. 임피던스 측정

  (1) 전기화학 임피던스 분광법(EIS)을 사용하여 0.1Hz에서 5KHz까지의 주파수 스윕을 통해 이루어 지고 이를 통해 배터리 내부의 저항을 평가하여 배터리의 상태와 효율을 이해하는 데 사용된다. 여기서 임피던스랑 전기회로에서 전류가 흐를 때 회로가 가하는 반발이나 저항을 나타내는 개념이며 사람의 몸 안 상태(근육량, 체지방량, 수분량 등)를 알기 위해 인바디 검사를 하는 것과 비슷
  
 라. 10개의 데이터 군은 각각 방전시키는 전압의 양(2.7V~2.0V)과 실험 온도조건(24°C, 44°C), 실험종료 EOL 기준 값(정적 용량의 30%, 50% 감소 등)등의 실험 조건 차이가 있어 이에 대한 비교 분석이 가능하다.   

 마. 반복된 충전 및 방전 사이클을 통해 배터리 잔여 충전 및 유효 수명(RUL)을 예측하기 위한 모델의 파라미터를 유추할 수있다. 

```{데이터 설명 및 원본 데이터 요약 결과}


  
3. 원본 데이터 요약 결과

 가. 11개의 변수 

   Voltage_measured: 측정된 배터리 단자 전압

   Current_measured: 측정된 배터리 출력 전류

   Temperature_measured: 측정된 배터리 온도

   Current_charge: 충전기에서 측정된 전류

   Voltage_charge: 충전기에서 측정된 전압

   Time: 주기 동안의 시간 벡터

   Capacity: 배터리의 용량 (배터리가 지정된 전압까지 방전)

   Sense_current: 감지 분기의 전류

   Battery_current: 배터리 분기의 전류

   Current_ratio: 감지 전류와 배터리 전류의 비율

   Battery_impedance: 측정된 원시 배터리 임피던스
 
   Rectified_impedance: 보정 및 평활화된 배터리 임피던스
  
```


```{데이터 분석 목적}

1. 리튬 이온 배터리의 용량, 임피던스 및 운영 조건을 활용하여 배터리의 성능 저하 및 수명을 예측

2. 유지보수 및 교체 전략을 최적화하여 효율성 향상과 비용 절감

3. 열화 패턴을 모델링 및 다중회귀모델을 포함한 통계적 방법을 사용하여 배터리 수명에 영향을 미치는 주요 요인들을 식별하고, 배터리 관리 및 운영 전략에 필요한 데이터 기반의 의사결정 지원

```


```{데이터 분석 절차}

1. 데이터 전처리 및 시각화

 가. 불필요한 데이터 제거, 결측치 처리, 이상치 검출 및 제거
 
 나. k-fold 교차검증을 통해 train 데이터와 test 데이터로 분할하여 모델 학습 시 사용
 
 다. 다양한 변수간의 상관관계를 시각화하여 연관성 파악
 
 라. 연관성이 보이는 변수들을 선택해서 표본상관계수 산출 후 상관분석 실시
 
 마. 시간에 따른 배터리의 용량(Capacity)의 변화를 시각화하여 열화 패턴 파악


2. 열화모형 추정
 
 가. 용량(Capacity) 데이터를 활용하여 배터리의 열화모형을 수립


3. 가설검정
 
 가. 두 가지 이상의 배터리 유형 또는 충전 조건에 대해 수명에 차이가 있는지 분산분석(ANOVA)검정 시행
 
 나. 수립된 열화 모형이 잘 적합하는지 적합도 검정 시행 


4. 다중회귀모형 학습

 가. 다양한 운영 조건에 대한 변수들을 기반으로 임피던스값을 추정하는 다중회귀모델 or 성능 저하를 예측하는 다중회귀모델

 나. 추정된 회귀계수의 유의성 검정
 
 다. 정규화 회귀분석(Lasso, Elastic Net, Ridge)으로 회귀계수의 크기에 제약을 두어 과대적합 및 과소적합 방지


5. 모델 평가 및 선택

 가. 회귀모형의 설명번수는 종속변수에 대해 통계적으로 유의미한 설명력을 갖는지 분산분석(ANOVA) 수행

 나. R^{2}adj을 사용하여 모델의 설명력을 평가

 다. 변수 선택법(전진선택법, 후진제거법, 단계적 선택법)을 통해 최적의 변수 조합 탐색

 라. MSE, MAE, RMSE 등을 계산하여 예측 성능 평가


```


```{도출 예정 결과물}

1. NASA의 배터리 열화 데이터를 활용하여 리튬 이온 배터리의 수명과 성능 저하를 예측하기 위한 데이터 기반 분석 예정. 

2. 수명 예측 모델: 본 프로젝트는 단순 선형 회귀 및 다중회귀 모델 등 여러 통계적 모형 사용하여 배터리의 수명을 예측할 것. 배터리의 용량 감소와 임피던스 증가 데이터를 토대로 성능 저하를 정량적으로 예측하며, 운영 조건에 따라 이러한 변화를 모델링.

3. 성능 저하 요인 분석: 파생 변수 생성 이후 배터리의 성능 저하에 영향을 미치는 주요 변수들을 식별하여, 이를 통해 배터리 관리 및 유지보수 비용 절감을 위한 최적화 전략 제시. 또한 군 간 분석(ANOVA)를 통해 배터리 유형 및 충전 조건, 실험 조건에 따른 평균 열화시간의 차이가 있는지 살펴 최적의 조건을 제시하며, 군 내 분산 분석을 통해 조건 내에서의 데이터 일관성 검토.

4. 분석 후 선형 회귀 직선을 통해 파생 변수 및 종속 변수 간의 관계가 선형적인지 판단하며, residual plot을 활용하여 데이터의 패턴, 이상치를 체크 예정. 또한 군 간 분석 시 Box plot을 활용하여 데이터의 분포를 살펴 여러 조건들 간의 관계 도식화 예정.

5. 분석 결과에서 얻은 인사이트를 바탕으로 실제 산업 공정에서 배터리의 지속 가능성을 높이고 유지보수 비용을 절감할 수 있는 최적화 된 유지보수 전략 제시.

```


```{임무분담}

->25%, 데이터전처리 + 파생변수 생성 : 나요셉
->25%, 데이터분석(가설검정) : 김지수
->25%, 데이터분석(회귀분석) : 김세현
->25%, Rmd 작성 & 발표 : 김윤희

```
